name: PR Label

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Add PR label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: pr

      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - 'src-tauri/**'
            frontend:
              - 'src/**'

      - name: Add Rust label
        if: steps.changes.outputs.rust == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: rust

      - name: Add Frontend label
        if: steps.changes.outputs.frontend == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: frontend